#!/bin/bash

if [ ! -d ~/.config/rde/ ]; then
	mkdir -p ~/.config/rde/
	cp /etc/rde/wallpaper.jpg  ~/.config/rde/wallpaper.jpg
fi

cp /etc/rde/configs/fbpanel.conf ~/.config/fbpanel/rde

export GTK_THEME=Nordic

compton --dbus --backend glx &

# Notifications
twmnd &

# Extras
guake &
conky --config /etc/rde/configs/conky.conf &
hsetroot -fill ~/.config/rde/wallpaper.jpg
gdesklets
paramano &
nm-applet &
fbpanel --profile rde &

# Custom pulseaudio stuff
pulseaudio -k
pulseaudio --start -nC -F /etc/rde/configs/pulseaudio.conf

# Tray Icons
pnmixer &

# WM
openbox --config-file /etc/rde/configs/openbox/rc.xml
